### ISSUE TITLE
Yoomoney link outdated

### ISSUE THREAD

**Issue by GriffinSego** [astrochili/defold-illumination#9]
I want to tip to support awesome extension development, but error message says "Эта ссылка уже не работает. У этого запроса денег есть срок действия  и он закончился. Попросите получателя создать новый запрос и отправить вам ссылку."

**Comment by astrochili** [comment]
Really? Thanks for the report, very strange and unstable. I can't reproduce it, but at the same time I don't want to confuse people.

Looks like I need to refresh it periodically to make it work. Such a case, of course, is no good. Perhaps it should be removed at all.
